const ROOT_URL = 'http://localhost:3001';
const URL_FETCH_JEDI = `${ROOT_URL}/jedi`;
const JEDI_FETCH = `JEDI_FETCH`;
const JEDI_ADD = `JEDI_ADD`;
const JEDI_DELETE = `JEDI_DELETE`;
const JEDI_FILTER = `JEDI_FILTER`;
const TEMPLATE_CHANGE = `TEMPLATE_CHANGE`;

export {
  JEDI_FETCH,
  URL_FETCH_JEDI,
  JEDI_ADD,
  JEDI_DELETE,
  JEDI_FILTER,
  TEMPLATE_CHANGE
}
